### PR TITLE
Force insertion of print_function and absolute_import

### PR DESCRIPTION
**Pull request by pikhovkin**
Added force insertion of print_function and absolute_import

### CODE REVIEW

**Comment by vstinner** [comment]
I dislike to *always* add print_function import. Sometimes, it's useless. I would prefer to only add it when it's really needed, like when the code uses "print >>file, msg" syntax or "print msg," syntax with trailing comma.

Please don't change the file format of tests.py. It seems like you converted it from Unix to MS-DOS newline format.

**Comment by vstinner** [comment]
I'm not sure about always adding absolute import neither. Or *maybe* if you really want it, I would prefer to exclude it from the "all" group, and require to enable it on demand.

**Comment by pikhovkin** [comment]
_print_function_ and _absolute_import_ are excluded from "all" group. Its must be explicitly indicated in order to call them.

**Comment by vstinner** [comment]
I heard that unicode_literals caused issues in Python 2. Are you a happy user of unicode_literals?

I dislike the overall PR. The sixer design is to produce the minimum number of changes to make a code almost compatible with Python 3. With this PR, you introduce changes (new __future__ imports) which can introduce regressions (unicode_literals, print_function) or simply be useless.

I would prefer to see a PR which only uses print_function when it's really required. As I wrote, to patch "print >>file, msg" for example... But this change is already implemented by the existing "print" operation of sixer... So I don't see the point of this PR.

**Comment by pikhovkin** [comment]
Large projects that work in production at many enterprises can not simply be replaced so easily, so support for both Python 2 and Python 3 is needed. We need a gradual transition to Python 3.
We need backward compatibility.

**Comment by pikhovkin** [comment]
I dont see problem in this PR. My operations (for __ future __) excluded from "all" group. 
These operations simplify backward compatibility support. Also allow to track incompatibility with python3, if someone in a team does not adhere to the agreement for python 3 (but writes under python 2, e.i. runs his code only for python 2).

**Comment by pikhovkin** [comment]
My operations (for __ future __) **excluded** from "all" group. Sixer users must to set explicitly ones.

**Comment by pikhovkin** [comment]
>  Are you a happy user of unicode_literals?

I do not need this function, but someone may need it. I added, so that someone does not have to insert it everywhere manually.

**Comment by vstinner** [comment]
Sorry for not being more reactive on this issue but I was very busy the last 2 weeks. This PR does at least two things: change how imports are inserted and add new operations. The new operations are not part of "all" but the doc wasn't updated properly. In short, I don't have the bandwith right now to fully review your non trivial PR. I'm fine that you closed it.

**Pull request closed without merging**
